language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install: true
script: true
deploy:
  provider: script
  script:
    - echo $rsync_password > rsyncd.passwd
    - rsync --password-file=./rsyncd.passwd -r ./src/ root@117.48.209.175::test_vue
