language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - echo $rsync_password > rsyncd.passwd
  - chown root:root rsyncd.passwd
  - chmod 600 rsyncd.passwd
  - npm install
script: 
  - npm run build
  - rsync --password-file=./rsyncd.passwd -r ./dist/ root@117.48.209.175::test_vue --delete