language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - echo $rsync_password2
  - echo $rsync_password2 > a.passwd
script: true
deploy:
  provider: script
  script: rsync --password-file=./a.passwd -r ./src/ root@117.48.209.175::test_vue --delete
