language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: sshpass -p kuaile1, scp -P 29134 -o stricthostkeychecking=no -r ./src/* root@117.48.209.175:/root/html/
