language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
    - "dist"
install:
  - echo $rsync_password2 > rsyncd.passwd
  - npm install
  - npm run build
script: true
deploy:
  provider: script
  script: ls
