language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - echo $rsync_password2 > rsyncd.passwd
  - npm install
  - npm run build
script: true
deploy:
  provider: script
  script: rsync --password-file=./rsyncd.passwd -r ../dist/ root@117.48.209.175::test_vue --delete
