language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
install: true
script: true
deploy:
  provider: script
  script: rsync -vzrtopg root@117.48.209.175::test_vue ./src/* --password-file=/etc/rsyncd.passwd --delete
